import {db} from "@/db"
import {invoices,students,branches} from "@/db/schema"
import {desc,eq} from "drizzle-orm"
import {getSession,branchScope} from "@/lib/auth"
import {redirect} from "next/navigation"

export default async function InvoicesPage(){
 const session=await getSession();if(!session)redirect("/login")
 const scope=branchScope(session)
 const rows=scope===null?await db.select({id:invoices.id,invoiceNumber:invoices.invoiceNumber,studentName:students.fullName,branchName:branches.name,totalFees:invoices.totalFees,discountAmount:invoices.discountAmount,paidAmount:invoices.paidAmount,remainingAmount:invoices.remainingAmount,createdAt:invoices.createdAt}).from(invoices).leftJoin(students,eq(invoices.studentId,students.id)).leftJoin(branches,eq(invoices.branchId,branches.id)).where(eq(invoices.isArchived,false)).orderBy(desc(invoices.createdAt)):await db.select({id:invoices.id,invoiceNumber:invoices.invoiceNumber,studentName:students.fullName,branchName:branches.name,totalFees:invoices.totalFees,discountAmount:invoices.discountAmount,paidAmount:invoices.paidAmount,remainingAmount:invoices.remainingAmount,createdAt:invoices.createdAt}).from(invoices).leftJoin(students,eq(invoices.studentId,students.id)).leftJoin(branches,eq(invoices.branchId,branches.id)).where(eq(invoices.branchId,scope!)).orderBy(desc(invoices.createdAt))
 return <div className="space-y-5"><div><h1 className="text-lg font-bold">الفواتير</h1><p className="text-sm text-zinc-500">الفواتير الصادرة من عمليات الدفع</p></div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[950px] text-right text-sm"><thead className="border-b bg-zinc-50"><tr><th className="px-4 py-3">رقم الفاتورة</th><th className="px-4 py-3">الطالب</th><th className="px-4 py-3">الفرع</th><th className="px-4 py-3">الرسوم</th><th className="px-4 py-3">الخصم</th><th className="px-4 py-3">الدفعة</th><th className="px-4 py-3">المتبقي</th><th className="px-4 py-3">التاريخ</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={8} className="px-4 py-10 text-center text-zinc-400">لا توجد فواتير</td></tr>:rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="px-4 py-3 font-medium">{r.invoiceNumber}</td><td className="px-4 py-3">{r.studentName??"—"}</td><td className="px-4 py-3">{r.branchName??"—"}</td><td className="px-4 py-3">{Number(r.totalFees).toFixed(2)}</td><td className="px-4 py-3">{Number(r.discountAmount).toFixed(2)}</td><td className="px-4 py-3">{Number(r.paidAmount).toFixed(2)}</td><td className="px-4 py-3 font-semibold">{Number(r.remainingAmount).toFixed(2)}</td><td className="px-4 py-3">{new Date(r.createdAt).toLocaleDateString("ar-LY")}</td></tr>)}</tbody></table></div></div>
}
