import {db} from "@/db"
import {sql} from "drizzle-orm"
import {branches} from "@/db/schema"
import {eq,asc} from "drizzle-orm"
import {requireRole,branchScope} from "@/lib/auth"
import {createInventoryItemAction,addInventoryTransactionAction,archiveInventoryItemAction} from "@/lib/actions/inventory-actions"
import {redirect} from "next/navigation"

export default async function Page(){
 const s=await requireRole(["admin","finance"]).catch(()=>null);if(!s)redirect("/dashboard");const scope=branchScope(s)
 const [bs,res]=await Promise.all([
  scope===null?db.select({id:branches.id,name:branches.name}).from(branches).where(eq(branches.status,"active")).orderBy(asc(branches.name)):db.select({id:branches.id,name:branches.name}).from(branches).where(eq(branches.id,scope)),
  scope===null?db.execute(sql`SELECT i.id,i.name,i.sku,i.category,i.unit,i.quantity,i.min_quantity,i.unit_cost,b.name AS branch_name FROM inventory_items i JOIN branches b ON b.id=i.branch_id WHERE i.is_archived=false ORDER BY i.name`):db.execute(sql`SELECT i.id,i.name,i.sku,i.category,i.unit,i.quantity,i.min_quantity,i.unit_cost,b.name AS branch_name FROM inventory_items i JOIN branches b ON b.id=i.branch_id WHERE i.is_archived=false AND i.branch_id=${scope} ORDER BY i.name`)
 ])
 const rows=res as unknown as Array<any>
 return <div dir="rtl" className="space-y-6"><div><h1 className="text-xl font-bold">المخزون والجرد</h1><p className="text-sm text-zinc-500">الأرصدة وحركات الإدخال والإخراج لكل فرع.</p></div>
 <form action={createInventoryItemAction} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-5"><input name="name" required placeholder="اسم الصنف" className="rounded border px-3 py-2 text-sm"/><input name="sku" placeholder="رمز الصنف" className="rounded border px-3 py-2 text-sm"/><input name="category" placeholder="التصنيف" className="rounded border px-3 py-2 text-sm"/><input name="unit" defaultValue="قطعة" placeholder="الوحدة" className="rounded border px-3 py-2 text-sm"/><input name="quantity" type="number" step="0.01" defaultValue="0" placeholder="الكمية" className="rounded border px-3 py-2 text-sm"/><input name="minQuantity" type="number" step="0.01" defaultValue="0" placeholder="حد التنبيه" className="rounded border px-3 py-2 text-sm"/><input name="unitCost" type="number" step="0.01" defaultValue="0" placeholder="تكلفة الوحدة" className="rounded border px-3 py-2 text-sm"/><select name="branchId" required className="rounded border px-3 py-2 text-sm">{bs.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input name="notes" placeholder="ملاحظات" className="rounded border px-3 py-2 text-sm"/><button className="rounded bg-zinc-900 px-4 py-2 text-sm text-white">إضافة صنف</button></form>
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[1000px] text-right text-sm"><thead className="border-b bg-zinc-50"><tr><th className="px-4 py-3">الصنف</th><th className="px-4 py-3">الرمز</th><th className="px-4 py-3">الفرع</th><th className="px-4 py-3">الكمية</th><th className="px-4 py-3">حد التنبيه</th><th className="px-4 py-3">التكلفة</th><th className="px-4 py-3">حركة</th><th className="px-4 py-3">إجراء</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b"><td className="px-4 py-3 font-medium">{r.name}</td><td className="px-4 py-3">{r.sku??"—"}</td><td className="px-4 py-3">{r.branch_name}</td><td className={"px-4 py-3 "+(Number(r.quantity)<=Number(r.min_quantity)?"font-bold text-red-600":"")}>{r.quantity} {r.unit}</td><td className="px-4 py-3">{r.min_quantity}</td><td className="px-4 py-3">{Number(r.unit_cost).toFixed(2)}</td><td className="px-4 py-3"><form action={addInventoryTransactionAction} className="flex flex-wrap gap-1"><input type="hidden" name="itemId" value={r.id}/><select name="transactionType" className="rounded border px-1 py-1 text-xs"><option value="in">إدخال</option><option value="out">إخراج</option></select><input name="quantity" required type="number" min="0.01" step="0.01" placeholder="كمية" className="w-20 rounded border px-1 py-1 text-xs"/><input name="date" required type="date" className="rounded border px-1 py-1 text-xs"/><button className="rounded bg-zinc-800 px-2 py-1 text-xs text-white">حفظ</button></form></td><td className="px-4 py-3"><form action={archiveInventoryItemAction}><input type="hidden" name="id" value={r.id}/><button className="rounded border px-2 py-1 text-xs">أرشفة</button></form></td></tr>)}</tbody></table></div></div>
}