'use client'

import { useEffect, useState, useTransition } from 'react'
import { createAcademicYear, createAttendance, createBranch, createDocument, createEmployee, createExpense, createInvoice, createStudent, listAcademicYears, listAttendance, listBranches, listDocuments, listEmployees, listExpenses, listInvoices, listStudents } from '@/app/actions/school'

type Tab = 'students' | 'branches' | 'years' | 'employees' | 'expenses' | 'invoices' | 'attendance' | 'documents'
const tabs: Record<Tab, string> = { students:'الطلاب', branches:'الفروع', years:'السنوات الدراسية', employees:'المعلمون والموظفون', expenses:'المصروفات', invoices:'الفواتير', attendance:'الحضور والغياب', documents:'الأرشيف والمستندات' }
const blank = { fullName:'', registrationNumber:'', grade:'', className:'', guardianName:'', guardianPhone:'', branchId:'', name:'', code:'', address:'', phone:'', startsOn:'', endsOn:'', jobTitle:'', notes:'', title:'', amount:'', expenseDate:'', category:'', invoiceNumber:'', dueDate:'', status:'pending', studentId:'', attendanceDate:'', fileUrl:'' }

export function AdminWorkspace() {
  const [tab, setTab] = useState<Tab>('students')
  const [form, setForm] = useState<Record<string,string>>(blank)
  const [rows, setRows] = useState<any[]>([])
  const [students, setStudents] = useState<any[]>([])
  const [branches, setBranches] = useState<any[]>([])
  const [message, setMessage] = useState('')
  const [pending, startTransition] = useTransition()

  const refresh = () => startTransition(async () => { const [s,b,y,e,x,i,a,d] = await Promise.all([listStudents(),listBranches(),listAcademicYears(),listEmployees(),listExpenses(),listInvoices(),listAttendance(),listDocuments()]); setStudents(s); setBranches(b); const map: Record<Tab,any[]> = {students:s,branches:b,years:y,employees:e,expenses:x,invoices:i,attendance:a,documents:d}; setRows(map[tab]) })
  useEffect(() => { refresh() }, [tab])
  const update = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }))
  const submit = (event: React.FormEvent) => { event.preventDefault(); setMessage(''); startTransition(async () => { const actions: Record<Tab, (input: unknown) => Promise<any>> = { students:createStudent, branches:createBranch, years:createAcademicYear, employees:createEmployee, expenses:createExpense, invoices:createInvoice, attendance:createAttendance, documents:createDocument }; const result = await actions[tab](form); setMessage(result.ok ? 'تم الحفظ بنجاح' : result.error || 'تعذر الحفظ'); if (result.ok) { setForm(blank); refresh() } }) }
  return <section className="mt-6 rounded-2xl border border-[#e8edf3] bg-white p-5 sm:p-6">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-extrabold text-[#203b64]">مركز إدارة المدرسة</h2><p className="mt-1 text-xs text-[#8b98aa]">إدارة البيانات الأساسية والمالية والحضور والأرشيف من مكان واحد.</p></div><button onClick={refresh} className="rounded-xl border border-[#dfe7ef] px-4 py-2 text-xs font-bold text-[#159a93]">تحديث البيانات</button></div>
    <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{Object.entries(tabs).map(([key,label]) => <button key={key} onClick={() => { setTab(key as Tab); setForm(blank); setMessage('') }} className={`shrink-0 rounded-xl px-3.5 py-2 text-xs font-bold ${tab===key ? 'bg-[#159a93] text-white' : 'bg-[#f4f8fa] text-[#6d7d92]'}`}>{label}</button>)}</div>
    <form onSubmit={submit} className="grid gap-3 rounded-2xl bg-[#f8fafc] p-4 sm:grid-cols-2 lg:grid-cols-4">
      {tab==='students' && <><Field label="اسم الطالب" value={form.fullName} onChange={v=>update('fullName',v)} required/><Field label="رقم القيد" value={form.registrationNumber} onChange={v=>update('registrationNumber',v)} required/><Field label="الصف" value={form.grade} onChange={v=>update('grade',v)}/><Field label="الفصل" value={form.className} onChange={v=>update('className',v)}/><Field label="ولي الأمر" value={form.guardianName} onChange={v=>update('guardianName',v)}/><Field label="هاتف ولي الأمر" value={form.guardianPhone} onChange={v=>update('guardianPhone',v)}/><Select label="الفرع" value={form.branchId} options={branches.map(b=>[b.id,b.name])} onChange={v=>update('branchId',v)}/></>}
      {tab==='branches' && <><Field label="اسم الفرع" value={form.name} onChange={v=>update('name',v)} required/><Field label="رمز الفرع" value={form.code} onChange={v=>update('code',v)} required/><Field label="العنوان" value={form.address} onChange={v=>update('address',v)}/><Field label="الهاتف" value={form.phone} onChange={v=>update('phone',v)}/></>}
      {tab==='years' && <><Field label="اسم السنة الدراسية" value={form.name} onChange={v=>update('name',v)} required/><Field label="تاريخ البداية" type="date" value={form.startsOn} onChange={v=>update('startsOn',v)}/><Field label="تاريخ النهاية" type="date" value={form.endsOn} onChange={v=>update('endsOn',v)}/></>}
      {tab==='employees' && <><Field label="الاسم" value={form.fullName} onChange={v=>update('fullName',v)} required/><Field label="الوظيفة" value={form.jobTitle} onChange={v=>update('jobTitle',v)} required/><Field label="الهاتف" value={form.phone} onChange={v=>update('phone',v)}/><Field label="الملاحظات" value={form.notes} onChange={v=>update('notes',v)}/></>}
      {tab==='expenses' && <><Field label="بيان المصروف" value={form.title} onChange={v=>update('title',v)} required/><Field label="المبلغ" type="number" value={form.amount} onChange={v=>update('amount',v)} required/><Field label="التاريخ" type="date" value={form.expenseDate} onChange={v=>update('expenseDate',v)}/><Field label="التصنيف" value={form.category} onChange={v=>update('category',v)}/></>}
      {tab==='invoices' && <><Field label="رقم الفاتورة" value={form.invoiceNumber} onChange={v=>update('invoiceNumber',v)} required/><Field label="المبلغ" type="number" value={form.amount} onChange={v=>update('amount',v)} required/><Field label="تاريخ الاستحقاق" type="date" value={form.dueDate} onChange={v=>update('dueDate',v)}/><Select label="الحالة" value={form.status} options={['pending','paid','overdue'].map(x=>[x, x==='pending'?'معلقة':x==='paid'?'مدفوعة':'متأخرة'])} onChange={v=>update('status',v)}/></>}
      {tab==='attendance' && <><Select label="الطالب" value={form.studentId} options={students.map(s=>[s.id,s.fullName])} onChange={v=>update('studentId',v)}/><Field label="التاريخ" type="date" value={form.attendanceDate} onChange={v=>update('attendanceDate',v)} required/><Select label="الحالة" value={form.status} options={['present','absent','late'].map(x=>[x,x==='present'?'حاضر':x==='absent'?'غائب':'متأخر'])} onChange={v=>update('status',v)}/><Field label="ملاحظة" value={form.notes} onChange={v=>update('notes',v)}/></>}
      {tab==='documents' && <><Field label="عنوان المستند" value={form.title} onChange={v=>update('title',v)} required/><Field label="التصنيف" value={form.category} onChange={v=>update('category',v)}/><Field label="رابط الملف" value={form.fileUrl} onChange={v=>update('fileUrl',v)}/></>}
      <button disabled={pending} className="rounded-xl bg-[#159a93] px-4 py-3 text-xs font-bold text-white disabled:opacity-50">{pending?'جارٍ الحفظ...':'حفظ البيانات'}</button>
    </form>
    {message && <p className="mt-3 rounded-xl bg-[#edf9f3] px-4 py-3 text-xs font-bold text-[#25875f]">{message}</p>}
    <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[620px] text-right text-xs"><thead><tr className="border-b border-[#edf0f4] text-[#8a97aa]"><th className="p-3">الاسم / البيان</th><th className="p-3">التفاصيل</th><th className="p-3">الحالة</th><th className="p-3">التاريخ</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||i} className="border-b border-[#f2f4f7] text-[#344b6b]"><td className="p-3 font-bold">{row.fullName||row.name||row.title||row.invoiceNumber||'—'}</td><td className="p-3">{row.registrationNumber||row.code||row.jobTitle||(row.amount?`${row.amount} ر.س`:row.category||'—')}</td><td className="p-3">{row.status|| (row.isCurrent?'الحالية':row.isActive?'نشط':'—')}</td><td className="p-3">{String(row.createdAt||row.expenseDate||row.attendanceDate||'').slice(0,10)||'—'}</td></tr>)}</tbody></table>{rows.length===0&&<p className="py-10 text-center text-sm font-semibold text-[#9aa6b5]">لم تتم إضافة أي بيانات بعد</p>}</div>
  </section>
}
function Field({label,value,onChange,type='text',required=false}:{label:string;value?:string;onChange:(v:string)=>void;type?:string;required?:boolean}) { return <label className="flex flex-col gap-1.5 text-xs font-bold text-[#52647c]"><span>{label}{required?' *':''}</span><input required={required} type={type} value={value||''} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-[#dfe7ef] bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-[#159a93]"/></label> }
function Select({label,value,options,onChange}:{label:string;value?:string;options:any[];onChange:(v:string)=>void}) { return <label className="flex flex-col gap-1.5 text-xs font-bold text-[#52647c]"><span>{label}</span><select value={value||''} onChange={e=>onChange(e.target.value)} className="rounded-xl border border-[#dfe7ef] bg-white px-3 py-2.5 text-sm font-normal"><option value="">اختر</option>{options.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label> }
