"use server"
import { db } from "@/db"
import { teachers, employees, subjects, classes, schedules, branches, auditLogs } from "@/db/schema"
import { and, eq } from "drizzle-orm"
import { revalidatePath } from "next/cache"
import { requireRole, branchScope } from "@/lib/auth"

export async function createTeacherAction(formData:FormData){const s=await requireRole(["admin","hr"]);const employeeId=Number(formData.get("employeeId"));if(!employeeId)return;const scope=branchScope(s);const [e]=await db.select({id:employees.id,branchId:employees.branchId}).from(employees).where(and(eq(employees.id,employeeId),eq(employees.isArchived,false))).limit(1);if(!e||(scope!==null&&e.branchId!==scope))throw new Error("FORBIDDEN");const [exists]=await db.select({id:teachers.id}).from(teachers).where(eq(teachers.employeeId,employeeId)).limit(1);if(!exists){const [t]=await db.insert(teachers).values({employeeId}).returning({id:teachers.id});await db.insert(auditLogs).values({userId:s.userId,action:"create",entityType:"teacher",entityId:t.id,description:"تمت إضافة معلم"})}revalidatePath("/hr/teachers");revalidatePath("/hr/schedules")}
export async function removeTeacherAction(formData:FormData){const s=await requireRole(["admin","hr"]);const id=Number(formData.get("id"));const [t]=await db.select({id:teachers.id,employeeId:teachers.employeeId}).from(teachers).where(eq(teachers.id,id)).limit(1);if(!t)return;const [e]=await db.select({branchId:employees.branchId}).from(employees).where(eq(employees.id,t.employeeId)).limit(1);const scope=branchScope(s);if(scope!==null&&e?.branchId!==scope)throw new Error("FORBIDDEN");await db.delete(teachers).where(eq(teachers.id,id));revalidatePath("/hr/teachers");revalidatePath("/hr/schedules")}
export async function createSubjectAction(formData:FormData){const s=await requireRole(["admin","hr"]);const name=String(formData.get("name")||"").trim();if(!name)return;const [r]=await db.insert(subjects).values({name,stage:String(formData.get("stage")||"").trim()||null,grade:String(formData.get("grade")||"").trim()||null}).returning({id:subjects.id});await db.insert(auditLogs).values({userId:s.userId,action:"create",entityType:"subject",entityId:r.id,description:"تمت إضافة مادة"});revalidatePath("/hr/subjects")}
export async function deleteSubjectAction(formData:FormData){await requireRole(["admin","hr"]);const id=Number(formData.get("id"));const [used]=await db.select({id:schedules.id}).from(schedules).where(eq(schedules.subjectId,id)).limit(1);if(used)throw new Error("المادة مرتبطة بجدول");await db.delete(subjects).where(eq(subjects.id,id));revalidatePath("/hr/subjects")}
export async function createClassAction(formData:FormData){const s=await requireRole(["admin","hr"]);const branchId=Number(formData.get("branchId"));const scope=branchScope(s);if(scope!==null&&scope!==branchId)throw new Error("FORBIDDEN");const [b]=await db.select({id:branches.id}).from(branches).where(and(eq(branches.id,branchId),eq(branches.status,"active"))).limit(1));const yearId=Number(formData.get("academicYearId"));if(!b||!yearId)throw new Error("بيانات غير صحيحة");const [r]=await db.insert(classes).values({name:String(formData.get("name")||"").trim(),grade:String(formData.get("grade")||"").trim()||null,branchId,academicYearId:yearId}).returning({id:classes.id});await db.insert(auditLogs).values({userId:s.userId,action:"create",entityType:"class",entityId:r.id,description:"تمت إضافة فصل"});revalidatePath("/hr/classes")}
export async function deleteClassAction(formData:FormData){const s=await requireRole(["admin","hr"]);const id=Number(formData.get("id"));const [r]=await db.select({id:classes.id,branchId:classes.branchId}).from(classes).where(eq(classes.id,id)).limit(1);const scope=branchScope(s);if(!r||(scope!==null&&r.branchId!==scope))throw new Error("FORBIDDEN");const [used]=await db.select({id:schedules.id}).from(schedules).where(eq(schedules.classId,id)).limit(1);if(used)throw new Error("الفصل مرتبط بجدول");await db.delete(classes).where(eq(classes.id,id));revalidatePath("/hr/classes")}
export async function createScheduleAction(formData:FormData){const s=await requireRole(["admin","hr"]);const classId=Number(formData.get("classId"));const teacherId=Number(formData.get("teacherId"));const subjectId=Number(formData.get("subjectId"));const scope=branchScope(s);const [c]=await db.select({branchId:classes.branchId}).from(classes).where(eq(classes.id,classId)).limit(1);if(!c||(scope!==null&&c.branchId!==scope))throw new Error("FORBIDDEN");const [t]=await db.select({id:teachers.id,branchId:employees.branchId}).from(teachers).innerJoin(employees,eq(teachers.employeeId,employees.id)).where(eq(teachers.id,teacherId)).limit(1);if(!t||(scope!==null&&t.branchId!==scope))throw new Error("FORBIDDEN");const [r]=await db.insert(schedules).values({teacherId,subjectId,classId,dayOfWeek:String(formData.get("dayOfWeek")),startTime:String(formData.get("startTime")),endTime:String(formData.get("endTime"))}).returning({id:schedules.id});await db.insert(auditLogs).values({userId:s.userId,action:"create",entityType:"schedule",entityId:r.id,description:"تم حفظ جدول دراسي"});revalidatePath("/hr/schedules")}
export async function deleteScheduleAction(formData:FormData){const s=await requireRole(["admin","hr"]);const id=Number(formData.get("id"));const [r]=await db.select({id:schedules.id,branchId:classes.branchId}).from(schedules).innerJoin(classes,eq(schedules.classId,classes.id)).where(eq(schedules.id,id)).limit(1);const scope=branchScope(s);if(!r||(scope!==null&&r.branchId!==scope))throw new Error("FORBIDDEN");await db.delete(schedules).where(eq(schedules.id,id));revalidatePath("/hr/schedules")}
