"use server"
import { db } from "@/db"
import { archiveDocuments, decisions, correspondence, auditLogs } from "@/db/schema"
import { eq } from "drizzle-orm"
import { revalidatePath } from "next/cache"
import { requireRole, branchScope } from "@/lib/auth"

export async function createArchiveDocumentAction(formData:FormData){
 const s=await requireRole(["admin","archive"]);const direction=String(formData.get("direction"));if(direction!=="incoming"&&direction!=="outgoing")throw new Error("بيانات غير صحيحة")
 const branchId=Number(formData.get("branchId"));const scope=branchScope(s);if(scope!==null&&scope!==branchId)throw new Error("FORBIDDEN")
 const [r]=await db.insert(archiveDocuments).values({direction,docNumber:String(formData.get("docNumber")),docDate:String(formData.get("docDate")),entity:String(formData.get("entity")),subject:String(formData.get("subject")),description:String(formData.get("description")||"").trim()||null,branchId,createdBy:s.userId}).returning({id:archiveDocuments.id})
 await db.insert(auditLogs).values({userId:s.userId,action:"create",entityType:"archive_document",entityId:r.id,description:"تم تسجيل مستند أرشيفي"});revalidatePath("/archive/"+direction);revalidatePath("/archive/search")
}
export async function archiveArchiveDocumentAction(formData:FormData){const s=await requireRole(["admin","archive"]);const id=Number(formData.get("id"));const [r]=await db.select({branchId:archiveDocuments.branchId}).from(archiveDocuments).where(eq(archiveDocuments.id,id)).limit(1);const scope=branchScope(s);if(!r||(scope!==null&&r.branchId!==scope))throw new Error("FORBIDDEN");await db.update(archiveDocuments).set({isArchived:true}).where(eq(archiveDocuments.id,id));revalidatePath("/archive/incoming");revalidatePath("/archive/outgoing");revalidatePath("/archive/search")}
export async function createDecisionAction(formData:FormData){const s=await requireRole(["admin","archive"]);const branchId=Number(formData.get("branchId"));const scope=branchScope(s);if(scope!==null&&scope!==branchId)throw new Error("FORBIDDEN");const [r]=await db.insert(decisions).values({decisionNumber:String(formData.get("decisionNumber")),decisionDate:String(formData.get("decisionDate")),subject:String(formData.get("subject")),details:String(formData.get("details")||"").trim()||null,branchId,createdBy:s.userId}).returning({id:decisions.id});await db.insert(auditLogs).values({userId:s.userId,action:"create",entityType:"decision",entityId:r.id,description:"تم تسجيل قرار"});revalidatePath("/archive/decisions")}
export async function archiveDecisionAction(formData:FormData){await requireRole(["admin","archive"]);const id=Number(formData.get("id"));await db.update(decisions).set({isArchived:true}).where(eq(decisions.id,id));revalidatePath("/archive/decisions")}
export async function createCorrespondenceAction(formData:FormData){const s=await requireRole(["admin","archive"]);const branchId=Number(formData.get("branchId"));const scope=branchScope(s);if(scope!==null&&scope!==branchId)throw new Error("FORBIDDEN");const [r]=await db.insert(correspondence).values({refNumber:String(formData.get("refNumber")),refDate:String(formData.get("refDate")),subject:String(formData.get("subject")),details:String(formData.get("details")||"").trim()||null,branchId,createdBy:s.userId}).returning({id:correspondence.id});await db.insert(auditLogs).values({userId:s.userId,action:"create",entityType:"correspondence",entityId:r.id,description:"تم تسجيل مراسلة"});revalidatePath("/archive/correspondence")}
export async function archiveCorrespondenceAction(formData:FormData){await requireRole(["admin","archive"]);const id=Number(formData.get("id"));await db.update(correspondence).set({isArchived:true}).where(eq(correspondence.id,id));revalidatePath("/archive/correspondence")}
